### ISSUE TITLE
How do you throw errors?

### ISSUE THREAD

**Issue by pyros2097** [graphql-go/graphql#28] opened 2015-10-26 12:14 UTC
I have a new graphql scalar type
```go
types.NewGraphQLScalarType(types.GraphQLScalarTypeConfig{
		Name: name,
		Serialize: func(value interface{}) interface{} {
			return value
		},
		ParseValue: func(value interface{}) interface{} {
			return value
		},
		ParseLiteral: func(valueAst ast.Value) interface{} {
			log.Info("Parsing Literal" + valueAst.GetKind())
			return errors.new("tester")
                        //panic("tester") works
		},
```
I construct an error and send it but in the response I don't get any error. But if I `panic` it seems to work. But isn't this not idiomatic go. Shouldn't the functions return an `(interface{}, error)`

**Comment by bbuck** [comment] 2015-10-27 17:42
I've noticed a similar issue with errors when passing `nil` as the value for a `types.GraphQLNonNull(...)` which should throw an error.

**Comment by sogko** [comment] 2015-10-28 17:15
Hi guys,

Currently user functions (such as `ParseLiteral`, `ResolveFn` etc) that are passed into configs and executed are caught/recovered by the `executor`. It will then be returned as `Errors` in `GraphQLResult` struct.

```go
type GraphQLResult struct {
	Data   interface{}                           `json:"data"`
	Errors []graphqlerrors.GraphQLFormattedError `json:"errors,omitempty"`
}
```

As to why the current implementation uses `panic` instead of returning a more idiomatic `error` value, I chose to defer from making that decision, instead made a straight port from `graphql-js` which throws error everywhere and anywhere, and wait to hear from the community :)

Personally I would love to see a move to a more go-idiomatic library as the project shapes itself, so I would vote for `(interface{}, error)` return signature for user functions as well.

@bbuck That's interesting. Could you share the JSON response from the query? (If this is off-topic, maybe in a separate issue)

Thanks guys!

**Comment by bbuck** [comment] 2015-10-28 17:57
I definitely think a move to a more idiomatic approach would be better. As far as I understood the graphql-js implementation was that it was only created to server as an example of how you could implement it. I'm pretty sure making the necessary alterations to bring a GraphQL server library to Go would make sense to apply Go processes to it.

There is some merit in keeping similarities, I'm not necessarily encouraging rebuilding everything, but where it makes sense I definitely think that's the best. And this is one place I think it does make sense. When I work in Go, I've very accustomed to `, err` assignments as well as returning an error from my own functions so it wouldn't be something I wouldn't already expect to do. However, writing a `panic` line in _production_ (so to speak) code would be something I'd be uncomfortable doing.

Also, @sogko, in regards to my last comment. Disregard. After running again to get your requested information I see the problem is with my previously posted issue on `GraphQLInt` ignoring other integer types. If I return a value, everything gives me 0, which is definitely wrong. I feel like it should have been throwing nil to begin with. But if I return `nil` directly the proper errors are reported.

**Comment by pyros2097** [comment] 2015-10-29 10:07
There seems to be another issue also if I panic in the ParseValue function it causes the process to crash. I think you are recovering only in the ParseLiteral function I will inspect more on this
```go
types.NewGraphQLScalarType(types.GraphQLScalarTypeConfig{
		Name: name,
		Serialize: func(value interface{}) interface{} {
			return value
		},
		ParseValue: func(value interface{}) interface{} {
                       panic("Not String Type")
		return value
		},
		ParseLiteral: func(valueAst ast.Value) interface{} {
                      return valueAst
		},
```

**Comment by sogko** [comment] 2015-11-06 05:34
Cleaning up the issues tracker. Closing this issue since the original issue brought up by @pyros2097 regarding return signature (i.e. `(interface{}, error)` has been bought up in #44. Consider continuing the discussion there.

Regarding the panic in `ParseValue()`, please consider creating another issue. If I have the time, I'll try to verify it and will open the issue for you.

Thanks and cheers guys!

**Closed by sogko** 2015-11-06 05:34 UTC
Labels: enhancement
