### ISSUE TITLE
Optimized Query performance / Query reducing

### ISSUE THREAD

**Issue by JesseFarebro** [graphql-go/graphql#90] opened 2015-12-06 08:23 UTC
I believe one thing missing from the current graphql-go library is the ability to either defer query execution to batch queries or some method of reducing complex queries so you aren't taking such a performance hit while retrieving items from a database. 

Now with the current state of GraphQL there seems to be a couple different ways to do this, I think we can get our own discussion going about how to implement similar functionality in Go and how such an API should look. Once I have a little more of an idea about a finalized API I have no problem sending in a pull request for further review.

I'll link here some current patterns to aid in the discussion:

Scala's primary GraphQL library [Sangria](http://sangria-graphql.org/) has probably the largest implementation of performance enhancing patterns. They have an entire section on [deffered values and resolvers](http://sangria-graphql.org/learn/#deferred-values-and-resolver). Essentially they have per type batched deferred values so you can perform say, one SQL query to fetch all these values and have the framework still marshall the proper results.

Shopify has made their own library for batching GraphQL requests in Ruby. It can be located [here](https://github.com/shopify/graphql-batch).

Here is the current discussion on the main graphql repository for reducing their executer queries: [graphql/graphql-js#26](https://github.com/graphql/graphql-js/issues/26).

**Comment by gburt** [comment] 2018-03-24 00:59
I believe this issue is a duplicate of #106

**Comment by chris-ramon** [comment] 2018-09-22 21:11
Thanks a lot for the great feedback guys! :+1: — I've created a new repo: [graphql-dataloader-sample](https://github.com/graphql-go/graphql-dataloader-sample) which shows how to do batching, closing this one.

**Closed by chris-ramon** 2018-09-22 21:11 UTC
