### ISSUE TITLE
Adding extra fields to errors

### ISSUE THREAD

**Issue by F21** [graphql-go/graphql#109] opened 2016-01-29 03:48 UTC
Let's say I have a graphql schema with a field that looks like this:

``` go
fields := graphql.Fields{
        "hello": &graphql.Field{
            Type: graphql.String,
            Resolve: func(p graphql.ResolveParams) (interface{}, error) {
                return nil, errors.New("Whoops! An error occurred")
            },
        },
    }
```

The result would be:

``` json
{
  "data": {
    "test": {
      "id": null,
    }
  },
  "errors": [
    {
      "message": "Whoops! An error occurred",
      "locations": [
      ]
    }
  ]
}
```

What I would like to do is to be able to add extra fields to the errors object. For example:

``` json
{
  "data": {
    "test": {
      "id": null,
    }
  },
  "errors": [
    {
      "message": "Whoops! An error occurred",
      "locations": [
      ],
      "field": "hello",
      "code": "WHOOPS_ERROR"
    }
  ]
}
```

It would be really cool if there's way to be able to add these extra fields into the error message when  an error happens.

**Comment by sogko** [comment] 2016-02-11 04:18
The `errors` field in the GraphQL response is defined in the [official spec](http://facebook.github.io/graphql/#sec-Errors) as follows:

> Every error must contain an entry with the key `message` with a string description of the error intended for the developer as a guide to understand and correct the error.

> If an error can be associated to a particular point in the requested GraphQL document, it should contain an entry with the key `locations` with a list of locations, where each location is a map with the keys line and column, both positive numbers starting from 1 which describe the beginning of an associated syntax element.

Having extra fields is actually addressed in the spec as well:
> GraphQL servers may provide additional entries to error as they choose to produce more helpful or machine‐readable errors, however future versions of the spec may describe additional entries to errors.

Would love to start a discussion if / how we want to achieve this.

Cheers!

**Comment by F21** [comment] 2016-02-11 05:48
Maybe the function's signature can become:

```go
func(p graphql.ResolveParams) (interface{}, error, interface{}) 
```

So, if there are any extra fields, you can do:

```go
type extraErrors struct {
  Code string `json:"code"`
  Field string `json:"field"`
}

fields := graphql.Fields{
        "hello": &graphql.Field{
            Type: graphql.String,
            Resolve: func(p graphql.ResolveParams) (interface{}, error, interface{}) {

                extras := &extraErrors{Code: "WHOOPS_ERROR", Field: "someField"}
                return nil, errors.New("Whoops! An error occurred")
            },
        },
    }
```

This means that existing resolvers will need to be updated to use:

```
return result, nil, nil
return nil, err, nil
```

**Comment by bbuck** [comment] 2016-02-11 05:48
I think `logrus` is a good place to start with this one.

```go
logrus.WithFields(logrus.Fields{
        "one": "two",
}).Info("Hey, it's a log")
```

Given the nature of `error` (it being an interface and al) we could then do something like this:

```go
type ErrorFields map[string]interface{}

type Error struct {
	Message string
	Fields ErrorFields
}

func (e *Error) Error() string {
	return e.Message
}

func (e *Error) WithFields(fields ErrorFields) {
	e.Fields = fields
}

func (e *Error) WithField(name string, value interface{}) {
	if e.Fields == nil {
		e.Fields = make(ErrorFields)
	}
	
	e.Fields[name] = value
}

func NewError(message string) *Error {
	return &Error{Message: message}
}
```

Usage from a Resolve:

```go
func (params graphql.ResolveParams) (interface{}, error) {
        return nil, graphql.NewError("this failed").WithFields(graphql.ErrorFields{
                "one": "two",
        })
}
```

Probably needs some significant cleaning up, or works. I think it's a simple and clean API.

**Comment by bbuck** [comment] 2016-02-11 05:52
@F21 I think changing the return signature for resolve functions would not be such a great idea. The biggest reason is I would imagine that additional error information is not a terribly common requirement so most of the time it would be `nil`. Basically I don't the use case is large enough to warrant a significant change like that - this feature should probably be implemented in the east invasive but still decently straight-forward way possible.

**Comment by F21** [comment] 2016-02-11 05:56
@bbuck After looking at your proposal, I agree!

**Comment by bbuck** [comment] 2016-02-11 06:12
By all means the credit should lie with Sirupsen who wrote `logrus` as I'm just ripping off his idea.

**Comment by mleonard87** [comment] 2016-03-30 11:51
@bbuck This solution looks good, also saves any regression issues for people that are already using this. Is anyone working on this? If not I'd like to take it on.

**Comment by mleonard87** [comment] 2016-04-04 12:35
Hi @bbuck and @sogko 

I've started implementing this issue and I'm pretty much done as per you suggestions above. However, I want to discuss how to handle marshalling of this. This new error type eventually gets converted to a `FormattedError` which, when running this as a web server will most likely eventually be Marshalled. Are we happy with an output format like:

```json
{
  "message": "an error occurred",
  "fields": {
    "customOne": "valueOne",
    "customTwo": "valueTwo:
  }
}
```

Or do we want to try and flatten it out like:

```json
{
  "message": "an error occurred",
  "customOne": "valueOne",
  "customTwo": "valueTwo:
}
```

If we want to do the latter how do we go about this in go so that it can be easily marshalled?

**Comment by bbuck** [comment] 2016-04-04 12:58
@mleonard87 I definitely think the tested approach feels a lot better than flattening it out in some way.

To your second question (even though I don't prefer this method) you'd want to implement the `enconding/json.Marshaler` interface which would allow the object to marshal itself in a flat structure as opposed to the automatic "nested" structure.

**Comment by mleonard87** [comment] 2016-04-04 13:09
Ok, excellent. Are you happy with the name `fields` or would you prefer `extra` or something else? 

And finally, what is the purpose of the `ErrorFields` type. Would it not be more flexible to simply make the `fields` argument `map[string]interface{}` itself?

**Comment by bbuck** [comment] 2016-04-04 14:47
@mleonard87 I'm not a decision maker for this project, I'd wait for @sogko or @chris-ramon to respond before finalizing any decisions.

That being said though, I think fields is clean enough -- and I'm not familiar enough at this moment to respond on `ErrorFields` but I'll give it a look at soon as I can and get back with you.

**Comment by philiplb** [comment] 2017-08-14 13:04
May I throw in that the flat structure would allow to (re-)implement all other GraphQL-APIs in this point? Having a fixed key here feels a bit like an artificial restriction.

**Comment by dvic** [comment] 2018-01-21 16:10
Any updates/decisions on this?

**Comment by plassa-b** [comment] 2018-02-14 09:33
Hey guys, I'd like to know how this issue is going, and also to give my input.

For me the flattening of fields isn't such a bad idea. I have to respect an error format like so 
```json
{
  "message": "Whoops! An error occurred",
  "locations": [
  ],
  "title": "hello",
  "code": 400
}
```
That means @mleonard87's first solution wouldn't work out for me.

I also see this #238 PR seems to implement a similar thing.
What do you guys think ?

**Comment by dvic** [comment] 2018-02-14 10:33
Just want to bring to your attention a PR I submitted related to this issue: https://github.com/graphql-go/graphql/pull/279.

This PR basically
* stores the original error in `FormattedError`
* uses `github.com/pkg/errors` in order to also have stack trace information

This enables me to render my domain errors differently, since I now have access to the actual underlying error.

**Comment by plassa-b** [comment] 2018-02-14 12:05
@dvic Could you provide a usage example ?
Let's say I return a custom error, what would I need to do for this error to end up looking like my one of the examples above ?

**Comment by dvic** [comment] 2018-02-14 12:39
@plassa-b It would look something like this where you handle the graphql query:

```go
res := graphql.Do(params)
// instead of rendering res directly, we're going to do something with the errors
if res.HasErrors() {
	var errorsArray []interface{}
	for _, err := range res.Errors {
		// errors.Cause(...) unwraps the underling error, e.g., if errors.Wrap(someErr) was used
		// we get 'someErr' instead of the wrapped error
		if err, ok := errors.Cause(err.Cause()).(interface {
			AsPublicJSON() []byte
		}); ok {
			errorsArray = append(errorsArray, json.RawMessage(err.AsPublicJSON()))
			continue
		}
		errorsArray = append(errorsArray, err)
	}
	writeJSON(rw, map[string]interface{}{"Errors": errorsArray})
} else {
	writeJSON(rw, map[string]interface{}{"Data": res.Data})
}
```

in the resolvers you can then return an error of the following type:
```go
type myErr struct {
	message string
	title   string
	code    int
}

func (e myErr) Error() string {
	return e.message
}

func (e myErr) AsPublicJSON() []byte {
	ret, err := json.Marshal(map[string]interface{}{
		"message":   e.message,
		"locations": []interface{}{},
		"title":     e.title,
		"code":      e.code,
	})
	if err != nil {
		panic(errors.WithStack(err))
	}
	return ret
}
```

Of course, you can also do the type check differently (on a specific error type, other methods, etc.).

**Comment by someanon** [comment] 2018-04-09 03:43
Hi all! What is the current status of this enhancement? We really need this to start using this graphql solution. Returning machine readable error codes - is essential part of any project.

**Comment by JulienBreux** [comment] 2018-04-20 11:05
I think that the proposition of @bbuck is crystal clear :)

But, to sum up I do not want to use the term "field", but rather "entries". From spec:

    future versions of the spec may describe additional entries to errors.

Because if you are an error between two fields, it's an entry error no a field error.

*Interface*
```go
type ErrorEntries map[string]interface{}

type Error struct {
        Message string
        Entries ErrorEntries
}

func (e *Error) Error() string {
        return e.Message
}

func (e *Error) WithEntries(entries ErrorEntries) {
        e.Entries = entries
}

func (e *Error) WithEntry(name string, value interface{}) {
        e.Entries[name] = value
}

func NewError(message string) *Error {
        return &Error{
                Message: message,
                Entries: make(ErrorEntries),
        }
}
```

*Resolver*

```go
func (params graphql.ResolveParams) (interface{}, error) {
        return nil, graphql.NewError("this failed").WithEntries(
                graphql.ErrorEntry{"email": "Must be unique"},
        )
}
```

@sogko or @chris-ramon can you give your vision/opinion?

_(as usual, a big thank you for the work)_

**Comment by rodrigo-brito** [comment] 2018-05-04 19:53
Great idea!

**Comment by JulienBreux** [comment] 2018-05-09 12:28
@sogko or @chris-ramon can you give your vision/opinion?

Do you need a PR?

**Comment by ccbrown** [comment] 2018-07-20 21:19
This is covered by the latest GraphQL spec. Your resolvers can now return errors that implement `gqlerrors.ExtendedError` to add an "extensions" field with arbitrary contents. For example:

```
  "errors": [
    {
      "message": "Name for character with ID 1002 could not be fetched.",
      "locations": [ { "line": 6, "column": 7 } ],
      "path": [ "hero", "heroFriends", 1, "name" ],
      "extensions": {
        "code": "CAN_NOT_FETCH_BY_ID",
        "timestamp": "Fri Feb 9 14:33:09 UTC 2018"
      }
    }
  ]
```

**Comment by 1046102779** [comment] 2018-07-20 23:42
ok, today i will check the problem. If confirmed, i will fallback codes and resolve relative bugs



At 2018-07-21 05:20:02, "Chris" <notifications@github.com> wrote:


This is covered by the latest GraphQL spec. Your resolvers can now return errors that implement gqlerrors.ExtendedError to add an "extensions" field with arbitrary contents. For example:

  "errors": [
    {
      "message": "Name for character with ID 1002 could not be fetched.",
      "locations": [ { "line": 6, "column": 7 } ],
      "path": [ "hero", "heroFriends", 1, "name" ],
      "extensions": {
        "code": "CAN_NOT_FETCH_BY_ID",
        "timestamp": "Fri Feb 9 14:33:09 UTC 2018"
      }
    }
  ]

**Comment by JulienBreux** [comment] 2018-07-22 20:56
@ccbrown Thanks, I think that this issue can be closed ;)

**Comment by Bleser92** [comment] 2018-08-18 08:08
Could you add an example?

**Comment by Fontinalis** [comment] 2019-04-05 08:18
> This is covered by the latest GraphQL spec. Your resolvers can now return errors that implement `gqlerrors.ExtendedError` to add an "extensions" field with arbitrary contents. For example:
> 
> ```
>   "errors": [
>     {
>       "message": "Name for character with ID 1002 could not be fetched.",
>       "locations": [ { "line": 6, "column": 7 } ],
>       "path": [ "hero", "heroFriends", 1, "name" ],
>       "extensions": {
>         "code": "CAN_NOT_FETCH_BY_ID",
>         "timestamp": "Fri Feb 9 14:33:09 UTC 2018"
>       }
>     }
>   ]
> ```

The issue has been resolved, so I'm closing it.

**Closed by Fontinalis** 2019-04-05 08:18 UTC
Labels: enhancement
