### ISSUE TITLE
Subscription Support

### ISSUE THREAD

**Issue by yhc44** [graphql-go/graphql#577] opened 2020-10-28 00:48 UTC
Hey, it is very sad, that this project seems not being actively maintained.

I used it for some days now and sadly there are some things missing (real subscriptions, field names in queries etc.) so im switching to nodejs in my graphql microservice.

**Comment by rick-meli** [comment] 2020-10-31 22:25
Hi, @yhc44 Seems I'm going to do the same 👎 . I really wanted my graphql microservice was built in golang. It's so sad.

**Comment by Fontinalis** [comment] 2020-11-01 11:20
Hey @yhc44 and @rick-meli ,

I share your thoughts.. A while back, this was part of the reasons why I started developing a GraphQL package in Go, with a similar, but different approaches. Since then, the core implementation got into a stable phase, and the additional features are still in development, but at my company we are confident enough to use it in projects that are we are currently working on. 

It has Subscriptions, Apollo Federation, field directives support, and many more features are coming, since I’m pumped to get them implemented, and personally we’ll also need them at work. So if you are still in the decision making, I would encourage you to check out the repo, see the examples, try it, check if it meet you needs and ask me any questions if you have. 

[rigglo/gql](https://github.com/rigglo/gql)

**Comment by giautm** [comment] 2020-11-01 14:39
Can you give a try will [gqlgen](https://gqlgen.com)? They generate go code from GraphQL schema, in-active development and subscription supported.

**Comment by chris-ramon** [comment] 2020-11-01 19:45
Hi @yhc44! –– Thanks for giving a try to the lib and sharing your thoughts:

***

> Hey, it is very sad, that this project seems not being actively maintained.

Actually we do try our best to actively maintain it, this is a concern that was raised in a previous issue: [Going out of life?](https://github.com/graphql-go/graphql/issues/527) and as pointed out in that issue hopefully we can catch-up on the awesome PRs that are to be reviewed & merge:

> We have many awesome contributors that were improving the library along the way, hopefully we can catch-up closing more issues and merging PRs.
> Ref: https://github.com/graphql-go/graphql/issues/527#issuecomment-581579779

***

> I used it for some days now and sadly there are some things missing (real subscriptions, field names in queries etc.)

> real subscriptions:

If you mean with `real subscriptions` having support for the `subscribe property` at the field definition level, yes this is a feature that hopefully we will be integrating soon via the [PR#495](https://github.com/graphql-go/graphql/pull/495).

But we do have `Subscriptions` support at the schema level since quite long time ago:

https://github.com/graphql-go/graphql/blob/2b0b7340d2285b861482047fbf5de0488e021bea/schema.go#L10

And here is a small working example: https://github.com/graphql-go/graphql/issues/49#issuecomment-404909227

***

> field names in queries

If with `field name in queries` your referring to [aliases](https://spec.graphql.org/draft/#sec-Field-Alias), we do have alias support on queries:

<img width="1155" alt="1" src="https://user-images.githubusercontent.com/1000404/97812557-f72f5300-1c4f-11eb-8199-049d3f5143df.png">


> etc.

If you could expand on this would be cool.

> so im switching to nodejs in my graphql microservice.

That would be a good alternative since [graphql-js](https://github.com/graphql/graphql-js) have the latest [GraphQL Spec](https://spec.graphql.org/draft/) features because the nature of being the reference implementation.

**Comment by yhc44** [comment] 2020-11-03 10:08
Hey @chris-ramon, thanks for your detailed answer.

With field names i mean for example

```go
subscription {
  onCreateCluster {
    id
  }
}
```

I implemented your pubsub example, which is working fine. But how can i retrieve the field id in this example? I dont want to return all fields that i have on the specific object.

**Comment by gerarts** [comment] 2021-04-26 09:47
Hey @chris-ramon, do you already have an ETA for PR #495? The last real commit to that PR was [almost a year ago](https://github.com/graphql-go/graphql/pull/495/commits/d54fb02f70601cc149c9cb057555a6564c4fad64) and as far as I can tell everything seems to work as intended (also see @bhoriuchi's [comment from November](https://github.com/graphql-go/graphql/pull/495#issuecomment-726365904)). Are we still waiting for something else? Thanks!

**Comment by chris-ramon** [comment] 2021-08-21 23:37
Resolved via: https://github.com/graphql-go/graphql/pull/495

**Closed by chris-ramon** 2021-08-21 23:37 UTC
Labels: question

**Comment by kamalkech** [comment] 2024-09-26 00:48
i guess should add new example of subscription / ws in folders example on official repo
